name: hi_docs
description: HiDocs Form Maker App
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  intl: ^0.20.2
  share_plus: ^10.1.4
  flutter_svg: ^2.0.10+1
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.4.0
  flutter_quill: ^11.5.1
  flutter_quill_extensions: ^11.0.0
  flutter_math_fork: ^0.7.4
  dart_quill_delta: ^10.8.3
  image_picker: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true