// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "HiDocs Support",
            "email": "support@hidocs.id"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/admin/creators": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "List form creators/users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.CreatorResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Create a new form creator account",
                "parameters": [
                    {
                        "description": "Create Creator Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/admin/creators/{creator_id}/status": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Update creator active/inactive status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Creator ID",
                        "name": "creator_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Status Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateCreatorStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/dashboard/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Get admin dashboard global statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/domain.AdminStats"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/admin/forms": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "List all system forms",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.FormResponseDTO"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/admin/forms/{form_id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Delete form as admin",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Form ID",
                        "name": "form_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/metrics/forms/{form_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Track live active students taking a specific exam form in real-time.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Telemetry \u0026 Monitoring"
                ],
                "summary": "Monitor live student activity on a specific form/exam",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Form ID UUID",
                        "name": "form_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.FormMetricsDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/admin/metrics/live-exams": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Monitor active exams currently in progress and distribution of students taking each exam.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Telemetry \u0026 Monitoring"
                ],
                "summary": "Get active live exams and real-time student distribution",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.LiveExamsResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/metrics/realtime": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Stream live telemetry via WebSocket or retrieve instantaneous snapshot JSON (RPS, Latency P95/P99, Active Users, Submissions).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Telemetry \u0026 Monitoring"
                ],
                "summary": "Stream or fetch real-time traffic telemetry metrics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.RealtimeMetricsResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/metrics/system": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Monitor CPU, memory allocations, goroutines count, and database connection pool status during peak load.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Telemetry \u0026 Monitoring"
                ],
                "summary": "Get Go runtime \u0026 PostgreSQL connection pool health metrics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.SystemMetricsResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/admin/metrics/traffic-history": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve traffic time-series (RPS, Latency ms, Error count) over the last 1-2 hours for Line Chart visualization.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Telemetry \u0026 Monitoring"
                ],
                "summary": "Get historical traffic time-series data for dashboard charts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Duration (e.g. 1h, today)",
                        "name": "duration",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.TrafficHistoryResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/forgot-password": {
            "post": {
                "description": "Generate password reset token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Request password reset",
                "parameters": [
                    {
                        "description": "Forgot Password Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ForgotPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/login": {
            "post": {
                "description": "Authenticate user and return JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login user",
                "parameters": [
                    {
                        "description": "Login Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.AuthResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/register": {
            "post": {
                "description": "Register a new user account. Generates a 6-digit OTP stored in Redis for 180 seconds.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Register user \u0026 send 6-digit OTP code to email",
                "parameters": [
                    {
                        "description": "Register Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/resend-otp": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Resend 6-digit OTP code",
                "parameters": [
                    {
                        "description": "Resend OTP Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ResendOTPRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/reset-password": {
            "post": {
                "description": "Reset user password using token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Reset password",
                "parameters": [
                    {
                        "description": "Reset Password Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ResetPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/verify-otp": {
            "post": {
                "description": "Validate 6-digit OTP code stored in Redis and return JWT Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Verify OTP code and activate registration",
                "parameters": [
                    {
                        "description": "Verify OTP Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.VerifyOTPRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.AuthResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/forms": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Forms"
                ],
                "summary": "List user forms ('My Forms')",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by status (DRAFT, ACTIVE, CLOSED)",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.FormResponseDTO"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Forms"
                ],
                "summary": "Create a new form",
                "parameters": [
                    {
                        "description": "Create Form Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateFormRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.FormResponseDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/forms/import-docx": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Forms"
                ],
                "summary": "Import form from Word .docx file",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Word Document (.docx)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.FormResponseDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/forms/{form_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Forms"
                ],
                "summary": "Get form details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Form ID",
                        "name": "form_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.FormResponseDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Forms"
                ],
                "summary": "Update form details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Form ID",
                        "name": "form_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Form Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateFormRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.FormResponseDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Forms"
                ],
                "summary": "Delete a form",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Form ID",
                        "name": "form_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/forms/{form_id}/analytics": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analytics"
                ],
                "summary": "Get real-time analytics for charts (Pie Chart score distribution, Question accuracy bar charts)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Form ID",
                        "name": "form_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/domain.FormAnalytics"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/forms/{form_id}/export": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Responses"
                ],
                "summary": "Export form responses to Excel or CSV",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Form ID",
                        "name": "form_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Export format ('xlsx' or 'csv', default: 'xlsx')",
                        "name": "format",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/api/v1/forms/{form_id}/questions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Questions"
                ],
                "summary": "List questions for a form",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Form ID",
                        "name": "form_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.QuestionDTO"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Questions"
                ],
                "summary": "Add a question to a form",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Form ID",
                        "name": "form_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create Question Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateQuestionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.QuestionDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/forms/{form_id}/responses": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Responses"
                ],
                "summary": "Get all responses for a form",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Form ID",
                        "name": "form_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.ResponseDetailDTO"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/forms/{form_id}/settings": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Forms"
                ],
                "summary": "Update form settings (Timer, Schedule, One-Time Submission, Randomization)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Form ID",
                        "name": "form_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Form Settings Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateFormSettingsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/domain.FormSettings"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/forms/{form_id}/submit": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Responses"
                ],
                "summary": "Submit form / exam answers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Form ID",
                        "name": "form_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Submit Form Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.SubmitFormRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.SubmitResponseResult"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/options/{option_id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Questions"
                ],
                "summary": "Delete a question option",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Option ID",
                        "name": "option_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/public/forms/{short_code}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Public"
                ],
                "summary": "Access public form by custom URL slug or short code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Custom URL Slug or Form ID",
                        "name": "short_code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.PublicFormDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/public/forms/{short_code}/qr": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Public"
                ],
                "summary": "Generate QR Code URL for public form access",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Custom URL Slug or Form ID",
                        "name": "short_code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/questions/upload-image": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Questions"
                ],
                "summary": "Upload image attachment for questions",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Image File (JPG, PNG, GIF)",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.UploadImageResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/questions/{question_id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Questions"
                ],
                "summary": "Update a question",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Question ID",
                        "name": "question_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Question Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateQuestionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.QuestionDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "Questions"
                ],
                "summary": "Delete a question",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Question ID",
                        "name": "question_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/responses/{response_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Responses"
                ],
                "summary": "Get individual response details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Response ID",
                        "name": "response_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ResponseDetailDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/responses/{response_id}/grade": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Responses"
                ],
                "summary": "Adjust score/grade manually for a response",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Response ID",
                        "name": "response_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Grade Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.GradeResponseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/superadmin/create-admin": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SuperAdmin"
                ],
                "summary": "Create a new admin account (SuperAdmin only)",
                "parameters": [
                    {
                        "description": "Create Admin Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/superadmin/list-admin": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "SuperAdmin"
                ],
                "summary": "List all admin accounts (SuperAdmin only)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/dto.UserResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/users/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Get current user profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Update profile",
                "parameters": [
                    {
                        "description": "Update Profile Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.UserResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/users/students/import": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Batch import students/users",
                "parameters": [
                    {
                        "description": "Import Students Payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ImportStudentsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.APIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.AdminStats": {
            "type": "object",
            "properties": {
                "active_exams": {
                    "type": "integer"
                },
                "total_creators": {
                    "type": "integer"
                },
                "total_forms": {
                    "type": "integer"
                },
                "total_responses": {
                    "type": "integer"
                },
                "total_users": {
                    "type": "integer"
                }
            }
        },
        "domain.FormAnalytics": {
            "type": "object",
            "properties": {
                "average_score": {
                    "type": "number"
                },
                "highest_score": {
                    "type": "number"
                },
                "lowest_score": {
                    "type": "number"
                },
                "question_breakdown": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/domain.QuestionAnalytics"
                    }
                },
                "total_responses": {
                    "type": "integer"
                }
            }
        },
        "domain.FormSettings": {
            "type": "object",
            "properties": {
                "auto_active_days": {
                    "type": "integer"
                },
                "duration_minutes": {
                    "type": "integer"
                },
                "end_time": {
                    "type": "string"
                },
                "form_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active_immediately": {
                    "type": "boolean"
                },
                "is_one_time_submission": {
                    "type": "boolean"
                },
                "randomize_options": {
                    "type": "boolean"
                },
                "randomize_questions": {
                    "type": "boolean"
                },
                "start_time": {
                    "type": "string"
                }
            }
        },
        "domain.FormStatus": {
            "type": "string",
            "enum": [
                "DRAFT",
                "ACTIVE",
                "CLOSED"
            ],
            "x-enum-varnames": [
                "StatusDraft",
                "StatusActive",
                "StatusClosed"
            ]
        },
        "domain.FormType": {
            "type": "string",
            "enum": [
                "SURVEY",
                "EXAM"
            ],
            "x-enum-varnames": [
                "TypeSurvey",
                "TypeExam"
            ]
        },
        "domain.QuestionAnalytics": {
            "type": "object",
            "properties": {
                "accuracy_rate": {
                    "type": "number"
                },
                "correct_count": {
                    "type": "integer"
                },
                "option_counts": {
                    "description": "Option ID -\u003e count",
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "question_id": {
                    "type": "string"
                },
                "question_text": {
                    "type": "string"
                },
                "total_answered": {
                    "type": "integer"
                }
            }
        },
        "domain.QuestionType": {
            "type": "string",
            "enum": [
                "SHORT_TEXT",
                "LONG_TEXT",
                "MULTIPLE_CHOICE",
                "CHECKBOXES",
                "DROPDOWN",
                "RATING",
                "YES_NO",
                "MATH",
                "CODE",
                "IMAGE"
            ],
            "x-enum-varnames": [
                "TypeShortText",
                "TypeLongText",
                "TypeMultipleChoice",
                "TypeCheckboxes",
                "TypeDropdown",
                "TypeRating",
                "TypeYesNo",
                "TypeMath",
                "TypeCode",
                "TypeImage"
            ]
        },
        "domain.UserRole": {
            "type": "string",
            "enum": [
                "superadmin",
                "admin",
                "user"
            ],
            "x-enum-varnames": [
                "RoleSuperAdmin",
                "RoleAdmin",
                "RoleUser"
            ]
        },
        "dto.AnswerDetailDTO": {
            "type": "object",
            "properties": {
                "answer_text": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_correct": {
                    "type": "boolean"
                },
                "points_earned": {
                    "type": "number"
                },
                "question_id": {
                    "type": "string"
                },
                "question_text": {
                    "type": "string"
                },
                "score_given": {
                    "type": "number"
                },
                "selected_option_id": {
                    "type": "string"
                },
                "selected_option_text": {
                    "type": "string"
                }
            }
        },
        "dto.AuthResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/dto.UserResponse"
                }
            }
        },
        "dto.CpuMetrics": {
            "type": "object",
            "properties": {
                "cores": {
                    "type": "integer"
                },
                "usage_percent": {
                    "type": "number"
                }
            }
        },
        "dto.CreateFormRequest": {
            "type": "object",
            "required": [
                "title",
                "type"
            ],
            "properties": {
                "custom_url": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "is_template": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 2
                },
                "type": {
                    "enum": [
                        "SURVEY",
                        "EXAM"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.FormType"
                        }
                    ]
                }
            }
        },
        "dto.CreateOptionRequest": {
            "type": "object",
            "required": [
                "option_text"
            ],
            "properties": {
                "is_correct": {
                    "type": "boolean"
                },
                "option_text": {
                    "type": "string"
                },
                "order_index": {
                    "type": "integer"
                }
            }
        },
        "dto.CreateQuestionRequest": {
            "type": "object",
            "required": [
                "question_text",
                "question_type"
            ],
            "properties": {
                "code_language": {
                    "type": "string"
                },
                "img_url": {
                    "type": "string"
                },
                "is_auto_scored": {
                    "type": "boolean"
                },
                "is_required": {
                    "type": "boolean"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CreateOptionRequest"
                    }
                },
                "order_index": {
                    "type": "integer"
                },
                "points": {
                    "type": "integer",
                    "minimum": 0
                },
                "question_text": {
                    "type": "string"
                },
                "question_type": {
                    "$ref": "#/definitions/domain.QuestionType"
                }
            }
        },
        "dto.CreatorResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.DBPoolMetrics": {
            "type": "object",
            "properties": {
                "active_connections": {
                    "type": "integer"
                },
                "idle_connections": {
                    "type": "integer"
                },
                "max_open_connections": {
                    "type": "integer"
                },
                "wait_count": {
                    "type": "integer"
                }
            }
        },
        "dto.ForgotPasswordRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "dto.FormMetricsDTO": {
            "type": "object",
            "properties": {
                "active_students": {
                    "type": "integer"
                },
                "average_score": {
                    "type": "number"
                },
                "form_id": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "total_submitted": {
                    "type": "integer"
                }
            }
        },
        "dto.FormResponseDTO": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "custom_url": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "form_settings": {
                    "$ref": "#/definitions/domain.FormSettings"
                },
                "id": {
                    "type": "string"
                },
                "is_template": {
                    "type": "boolean"
                },
                "questions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.QuestionDTO"
                    }
                },
                "response_count": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/domain.FormStatus"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/domain.FormType"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "dto.GradeResponseRequest": {
            "type": "object",
            "properties": {
                "total_score": {
                    "type": "number",
                    "minimum": 0
                }
            }
        },
        "dto.HttpStatusBreakdown": {
            "type": "object",
            "properties": {
                "2xx_success": {
                    "type": "integer"
                },
                "4xx_client_err": {
                    "type": "integer"
                },
                "5xx_server_err": {
                    "type": "integer"
                }
            }
        },
        "dto.ImportStudentsRequest": {
            "type": "object",
            "required": [
                "students"
            ],
            "properties": {
                "students": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.RegisterRequest"
                    }
                }
            }
        },
        "dto.LatencyStats": {
            "type": "object",
            "properties": {
                "avg_ms": {
                    "type": "number"
                },
                "p95_ms": {
                    "type": "number"
                },
                "p99_ms": {
                    "type": "number"
                }
            }
        },
        "dto.LiveExamDTO": {
            "type": "object",
            "properties": {
                "active_students": {
                    "type": "integer"
                },
                "creator_name": {
                    "type": "string"
                },
                "ends_at": {
                    "type": "string"
                },
                "form_id": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "submitted_count": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "total_target_students": {
                    "type": "integer"
                }
            }
        },
        "dto.LiveExamsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.LiveExamDTO"
                    }
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "dto.MemoryMetrics": {
            "type": "object",
            "properties": {
                "alloc_mb": {
                    "type": "number"
                },
                "gc_cycles": {
                    "type": "integer"
                },
                "sys_mb": {
                    "type": "number"
                }
            }
        },
        "dto.OptionDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "is_correct": {
                    "type": "boolean"
                },
                "option_text": {
                    "type": "string"
                },
                "order_index": {
                    "type": "integer"
                },
                "question_id": {
                    "type": "string"
                }
            }
        },
        "dto.PublicFormDTO": {
            "type": "object",
            "properties": {
                "custom_url": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "form_settings": {
                    "$ref": "#/definitions/dto.PublicFormSettings"
                },
                "id": {
                    "type": "string"
                },
                "is_template": {
                    "type": "boolean"
                },
                "questions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.PublicQuestionDTO"
                    }
                },
                "status": {
                    "$ref": "#/definitions/domain.FormStatus"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/domain.FormType"
                }
            }
        },
        "dto.PublicFormSettings": {
            "type": "object",
            "properties": {
                "auto_active_days": {
                    "type": "integer"
                },
                "duration_minutes": {
                    "type": "integer"
                },
                "end_time": {
                    "type": "string"
                },
                "is_active_immediately": {
                    "type": "boolean"
                },
                "is_one_time_submission": {
                    "type": "boolean"
                },
                "randomize_options": {
                    "type": "boolean"
                },
                "randomize_questions": {
                    "type": "boolean"
                },
                "start_time": {
                    "type": "string"
                }
            }
        },
        "dto.PublicOptionDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "option_text": {
                    "type": "string"
                },
                "order_index": {
                    "type": "integer"
                }
            }
        },
        "dto.PublicQuestionDTO": {
            "type": "object",
            "properties": {
                "code_language": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "img_url": {
                    "type": "string"
                },
                "is_auto_scored": {
                    "type": "boolean"
                },
                "is_required": {
                    "type": "boolean"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.PublicOptionDTO"
                    }
                },
                "order_index": {
                    "type": "integer"
                },
                "points": {
                    "type": "integer"
                },
                "question_text": {
                    "type": "string"
                },
                "question_type": {
                    "$ref": "#/definitions/domain.QuestionType"
                }
            }
        },
        "dto.QuestionDTO": {
            "type": "object",
            "properties": {
                "code_language": {
                    "type": "string"
                },
                "form_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "img_url": {
                    "type": "string"
                },
                "is_auto_scored": {
                    "type": "boolean"
                },
                "is_required": {
                    "type": "boolean"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.OptionDTO"
                    }
                },
                "order_index": {
                    "type": "integer"
                },
                "points": {
                    "type": "integer"
                },
                "question_text": {
                    "type": "string"
                },
                "question_type": {
                    "$ref": "#/definitions/domain.QuestionType"
                }
            }
        },
        "dto.RealtimeMetricsData": {
            "type": "object",
            "properties": {
                "active_connections": {
                    "type": "integer"
                },
                "active_users": {
                    "type": "integer"
                },
                "average_response_time_ms": {
                    "type": "number"
                },
                "error_rate_percent": {
                    "type": "number"
                },
                "http_status_breakdown": {
                    "$ref": "#/definitions/dto.HttpStatusBreakdown"
                },
                "latency": {
                    "$ref": "#/definitions/dto.LatencyStats"
                },
                "p95_response_time_ms": {
                    "type": "number"
                },
                "p99_response_time_ms": {
                    "type": "number"
                },
                "requests_per_second": {
                    "type": "number"
                },
                "submissions_per_minute": {
                    "type": "integer"
                },
                "system_metrics": {
                    "$ref": "#/definitions/dto.SystemMetricsDetail"
                },
                "timestamp": {
                    "type": "string"
                },
                "total_submissions_today": {
                    "type": "integer"
                }
            }
        },
        "dto.RealtimeMetricsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.RealtimeMetricsData"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                }
            }
        },
        "dto.ResendOTPRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "dto.ResetPasswordRequest": {
            "type": "object",
            "required": [
                "new_password",
                "token"
            ],
            "properties": {
                "new_password": {
                    "type": "string",
                    "minLength": 6
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "dto.ResponseDetailDTO": {
            "type": "object",
            "properties": {
                "answers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.AnswerDetailDTO"
                    }
                },
                "form_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_auto_submitted": {
                    "type": "boolean"
                },
                "respondent_email": {
                    "type": "string"
                },
                "submitted_at": {
                    "type": "string"
                },
                "total_score": {
                    "type": "number"
                }
            }
        },
        "dto.SubmitAnswerDetail": {
            "type": "object",
            "required": [
                "question_id"
            ],
            "properties": {
                "answer_text": {
                    "type": "string"
                },
                "question_id": {
                    "type": "string"
                },
                "selected_option_id": {
                    "type": "string"
                }
            }
        },
        "dto.SubmitFormRequest": {
            "type": "object",
            "required": [
                "answers",
                "respondent_email"
            ],
            "properties": {
                "answers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.SubmitAnswerDetail"
                    }
                },
                "is_auto_submitted": {
                    "type": "boolean"
                },
                "passcode": {
                    "type": "string"
                },
                "respondent_email": {
                    "type": "string"
                }
            }
        },
        "dto.SubmitResponseResult": {
            "type": "object",
            "properties": {
                "is_auto_submitted": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "response_id": {
                    "type": "string"
                },
                "submitted_at": {
                    "type": "string"
                },
                "total_score": {
                    "type": "number"
                }
            }
        },
        "dto.SystemMetricsData": {
            "type": "object",
            "properties": {
                "cpu": {
                    "$ref": "#/definitions/dto.CpuMetrics"
                },
                "database_pool": {
                    "$ref": "#/definitions/dto.DBPoolMetrics"
                },
                "goroutines_count": {
                    "type": "integer"
                },
                "memory": {
                    "$ref": "#/definitions/dto.MemoryMetrics"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "dto.SystemMetricsDetail": {
            "type": "object",
            "properties": {
                "cpu_usage_percent": {
                    "type": "number"
                },
                "db_idle_connections": {
                    "type": "integer"
                },
                "db_open_connections": {
                    "type": "integer"
                },
                "memory_usage_mb": {
                    "type": "number"
                }
            }
        },
        "dto.SystemMetricsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.SystemMetricsData"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.TimeSeriesPoint": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "integer"
                },
                "latency_ms": {
                    "type": "number"
                },
                "rps": {
                    "type": "number"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "dto.TrafficHistoryData": {
            "type": "object",
            "properties": {
                "time_series": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.TimeSeriesPoint"
                    }
                }
            }
        },
        "dto.TrafficHistoryResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.TrafficHistoryData"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "dto.UpdateCreatorStatusRequest": {
            "type": "object",
            "properties": {
                "is_active": {
                    "type": "boolean"
                }
            }
        },
        "dto.UpdateFormRequest": {
            "type": "object",
            "required": [
                "status",
                "title",
                "type"
            ],
            "properties": {
                "custom_url": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "is_template": {
                    "type": "boolean"
                },
                "status": {
                    "enum": [
                        "DRAFT",
                        "ACTIVE",
                        "CLOSED"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.FormStatus"
                        }
                    ]
                },
                "title": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 2
                },
                "type": {
                    "enum": [
                        "SURVEY",
                        "EXAM"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/domain.FormType"
                        }
                    ]
                }
            }
        },
        "dto.UpdateFormSettingsRequest": {
            "type": "object",
            "properties": {
                "auto_active_days": {
                    "type": "integer"
                },
                "duration_minutes": {
                    "type": "integer"
                },
                "end_time": {
                    "type": "string"
                },
                "is_active_immediately": {
                    "type": "boolean"
                },
                "is_one_time_submission": {
                    "type": "boolean"
                },
                "randomize_options": {
                    "type": "boolean"
                },
                "randomize_questions": {
                    "type": "boolean"
                },
                "start_time": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateProfileRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2
                }
            }
        },
        "dto.UpdateQuestionRequest": {
            "type": "object",
            "required": [
                "question_text",
                "question_type"
            ],
            "properties": {
                "code_language": {
                    "type": "string"
                },
                "img_url": {
                    "type": "string"
                },
                "is_auto_scored": {
                    "type": "boolean"
                },
                "is_required": {
                    "type": "boolean"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.CreateOptionRequest"
                    }
                },
                "order_index": {
                    "type": "integer"
                },
                "points": {
                    "type": "integer",
                    "minimum": 0
                },
                "question_text": {
                    "type": "string"
                },
                "question_type": {
                    "$ref": "#/definitions/domain.QuestionType"
                }
            }
        },
        "dto.UploadImageResponse": {
            "type": "object",
            "properties": {
                "img_url": {
                    "type": "string"
                }
            }
        },
        "dto.UserResponse": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/domain.UserRole"
                }
            }
        },
        "dto.VerifyOTPRequest": {
            "type": "object",
            "required": [
                "email",
                "otp_code"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "otp_code": {
                    "type": "string"
                }
            }
        },
        "response.APIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "errors": {},
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "HiDocs Backend API (Form & Exam Maker)",
	Description:      "High-performance backend API for HiDocs Form & Exam Maker application using Golang and Domain-Driven Design (DDD).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
